apiVersion: v1
kind: Secret
metadata:
  name: teaching-platform-secrets
  namespace: teaching-platform
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
  MYSQL_PASSWORD: "${DB_PASSWORD}"
  AI_API_KEY: "${AI_API_KEY}"
  JUDGE0_API_KEY: "${JUDGE0_API_KEY}"
  INTERNAL_API_KEY: "${INTERNAL_API_KEY}"
